name: go
description: Pure travel app.

publish_to: 'none'




version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  google_maps_flutter: ^1.0.3
  cupertino_icons: ^0.1.3
  animations: ^1.1.2
  flutter_svg: ^0.19.1
  page_transition: ^1.1.5
  font_awesome_flutter: ^8.10.0
  url_launcher: ^5.7.8

  firebase_core : ^0.5.0
  firebase_auth: ^0.18.3
  firebase_storage: ^5.2.0
  google_sign_in: ^4.5.6

  # firebase_database: ^4.3.0
  shared_preferences: ^0.5.12+4
  delayed_display: ^1.1.0
  flutter_staggered_animations: ^0.1.2

  flutter_circle_color_picker: ^0.2.0
  image_picker: ^0.6.7+11

  provider: ^4.3.2+3
  http: ^0.12.2

  location: ^3.0.0
  icofont_flutter: ^1.3.0
  

  webview_flutter: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  image_path: "assets/icons/go-icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - 'assets/webconstructor/'

    
    # assets for menu screen
    - 'assets/icons/menu/earth.png' 
    - 'assets/icons/menu/home.png'
    - 'assets/icons/menu/book.png'
    - 'assets/icons/menu/game.png'

    - 'assets/icons/menu/earth-decoration.png' 
    - 'assets/icons/menu/home-decoration.png'
    - 'assets/icons/menu/book-decoration.png'
    - 'assets/icons/menu/game-decoration.png'
    # Standart sad face for mistakes
    - 'assets/icons/sad_face.svg'
    # Standart user avatar
    - 'assets/icons/avatar.png'
    - 'assets/icons/denis.jpg'
    # Dictionary
    - 'assets/icons/smart_dict.jpg'
    - 'assets/icons/info_dict.jpg'
    # Google logo 
    - 'assets/icons/home/google_logo.png'
    # Avatar Placeholder
    - 'assets/icons/avatar-placeholder.jpg'



    - 'assets/icons/coffe.png'

    
  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Regular.ttf
        - asset: assets/fonts/Comfortaa-Bold.ttf
          weight: 700

