name: go
description: Pure travel app.

publish_to: 'none'




version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  animations: ^1.1.2
  flutter_svg: ^0.19.1
  page_transition: ^1.1.5
  font_awesome_flutter: ^8.10.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    # assets for menu screen
    - 'assets/icons/menu/earth.png' 
    - 'assets/icons/menu/home.png'
    - 'assets/icons/menu/book.png'
    - 'assets/icons/menu/game.png'

    - 'assets/icons/menu/earth-decoration.png' 
    - 'assets/icons/menu/home-decoration.png'
    - 'assets/icons/menu/book-decoration.png'
    - 'assets/icons/menu/game-decoration.png'
    # Standart sad face for mistakes
    - 'assets/icons/sad_face.svg'
    # Standart user avatar
    - 'assets/icons/avatar.png'
    - 'assets/icons/denis.jpg'

  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Regular.ttf
        - asset: assets/fonts/Comfortaa-Bold.ttf
          weight: 700