/// Flutter icons FilterIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FilterIcons
///      fonts:
///       - asset: fonts/FilterIcons.ttf
///
/// 
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class FilterIcons {
  FilterIcons._();

  static const _kFontFam = 'FilterIcons';
  static const _kFontPkg = null;

  static const IconData shopify = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hospital_cross = IconData(0xea07, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bank = IconData(0xf19c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hospital_alt = IconData(0xf47d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
